"""The mechanism-world substrate: a hidden web of parts that influence each other,
generated by a compact module grammar, plus the dumb-deterministic core the judge needs.

The hidden mechanism is a **forest of rooted modules** over N global nodes. An edge i->j
means "part i directly influences part j". The agent never sees the wiring; it probes a
node and sees that node's **reachable set** (everything it eventually influences — its
descendants), and from those ripples it must reconstruct the *direct* edges under a scarce
probe budget. Score = F1 of the reconstructed edge set against the truth.

Why this shape (designed down from the PI's criterion: taste lives in *deciding where to
look*, and a weak model can be good at that because it is disposition, not horsepower):

- **The false compass is intrinsic.** Poking a module root lights up the whole module
  (max salience) but pins almost no *direct* edges — it cannot tell i->j->k apart from
  i->j, i->k. The genuinely informative pokes are the quiet interior ones whose reachable
  sets let you do the transitive reduction. So salience (how much lights up) is
  anti-correlated with information (edges disambiguated) — deception falls out of the
  structure, it is not bolted on. `naive_floor` measures exactly this trap.
- **Branching ambiguity is intrinsic.** Which poke is most informative depends on the
  partial wiring you have already inferred; there is no fixed "always poke X". (This is the
  threshold the tape failed: no five-line policy is optimal, because the value of a poke is
  belief-dependent.)
- **Inferable, no sum-of-two ghosts.** Every hidden edge leaves a trace in some poke's
  reachable set; nothing here can only be got by luck. You just cannot afford to catch all
  of it, so you must bet where to spend — research, not guesswork.
- **Ramp, not cliff.** Modules are independent components, so fully inferring an f-fraction
  of them recovers ~f of the edges -> coverage is ~linear in the fraction inferred
  (`ramp_curve`). A weak learner can climb.
- **Cheap, uncapped growth.** A spec is a few (kind, size) module descriptors; a pure
  stdlib expander realizes the forest. Generation is free; only playing costs. Complexity
  grows by composing deeper/larger modules with no ceiling (the difficulty dial).

References are computed by **simulating policies** on the fixed graph (floor / realizable /
omniscient), per the slice-3 lesson "compute references by verified simulation, not a
clever closed form" — the integrity floor is intact (dumb, deterministic, agent-inaccessible
f(spec, budget)); only playing the world with an LLM costs tokens.
"""

from dataclasses import dataclass
from itertools import combinations
from typing import Dict, FrozenSet, List, Set, Tuple

KINDS = ("chain", "star", "tree")


@dataclass(frozen=True)
class Module:
    kind: str   # one of KINDS
    size: int   # number of nodes in this module (>= 2)


@dataclass(frozen=True)
class MechSpec:
    """A compact, smith-proposable world: a handful of modules + a scarce probe budget.
    Global node ids 0..N-1 are assigned to modules in order."""
    name: str
    modules: Tuple[Module, ...]
    budget: int

    @property
    def N(self) -> int:
        return sum(m.size for m in self.modules)


# ---------------------------------------------------------------------------
# Deterministic expander: spec -> the hidden forest (parents, edges, reachability).
# A forest (each node has <= 1 parent) keeps reachable sets laminar, so transitive
# reduction is exact and cheap, and module components stay independent (the ramp).
# ---------------------------------------------------------------------------
def _local_parents(kind: str, n: int) -> List[int]:
    """Parent of each local node (root = -1) for a module of `kind`, size `n`."""
    if kind == "chain":
        return [-1] + [i - 1 for i in range(1, n)]           # 0->1->2->...
    if kind == "star":
        return [-1] + [0 for _ in range(1, n)]               # 0 drives all others
    if kind == "tree":
        return [-1] + [(i - 1) // 2 for i in range(1, n)]    # balanced binary
    raise ValueError(f"unknown module kind {kind!r}")


def expand(spec: MechSpec) -> Tuple[List[int], FrozenSet[Tuple[int, int]], List[FrozenSet[int]],
                                    List[int]]:
    """Realize the hidden mechanism (the answer key — world plane only).

    Returns (parent, edges, reach, module_of):
      parent[v]    : global parent id of node v, or -1 if a module root
      edges        : frozenset of direct (parent, child) global edges
      reach[v]     : frozenset of v's descendants (what poking v lights up)
      module_of[v] : index of the module v belongs to
    """
    parent: List[int] = []
    module_of: List[int] = []
    children: Dict[int, List[int]] = {}
    off = 0
    for mi, m in enumerate(spec.modules):
        locals_ = _local_parents(m.kind, m.size)
        for li, lp in enumerate(locals_):
            gid = off + li
            gp = -1 if lp < 0 else off + lp
            parent.append(gp)
            module_of.append(mi)
            children.setdefault(gp, []).append(gid)
        off += m.size
    edges = frozenset((p, c) for c, p in enumerate(parent) if p >= 0)
    reach = _reachability(len(parent), children)
    return parent, edges, reach, module_of


def _reachability(n: int, children: Dict[int, List[int]]) -> List[FrozenSet[int]]:
    """reach[v] = all descendants of v (DFS over the children adjacency)."""
    reach: List[Set[int]] = [set() for _ in range(n)]

    def dfs(v: int) -> Set[int]:
        if reach[v]:
            return reach[v]
        acc: Set[int] = set()
        for c in children.get(v, []):
            acc.add(c)
            acc |= dfs(c)
        reach[v] = acc
        return acc

    for v in range(n):
        dfs(v)
    return [frozenset(s) for s in reach]


# ---------------------------------------------------------------------------
# The dumb-deterministic core: transitive reduction + F1 (pure f(structure, observations)).
# ---------------------------------------------------------------------------
def transitive_reduction(nodes: Set[int], reach: List[FrozenSet[int]]) -> Set[Tuple[int, int]]:
    """Direct edges recoverable from the FULL reachable sets of `nodes`: i->j is direct iff
    j in reach[i] and no k in reach[i] (k != j) also reaches j. Exact on a forest -> recovers
    exactly the parent->child edges among fully-probed nodes. This is the *true compass*:
    edges fall out only by comparing reachable sets, never from a single loud poke."""
    direct: Set[Tuple[int, int]] = set()
    for i in nodes:
        for j in reach[i]:
            if not any(j in reach[k] for k in reach[i] if k != j and k in nodes):
                direct.add((i, j))
    return direct


def f1(pred: Set[Tuple[int, int]], true: FrozenSet[Tuple[int, int]]) -> Tuple[float, float, float]:
    """(f1, precision, recall) of a predicted edge set against the truth. Guess-nothing ->
    recall 0 -> F1 0; guess-everything -> precision low -> F1 low. Only true structure scores
    -- sparse-robust, so there is no 'mostly-absent' free floor (the Chapter-1 trap)."""
    if not pred:
        return 0.0, 0.0, 0.0
    tp = len(pred & true)
    if tp == 0:
        return 0.0, 0.0, 0.0
    prec, rec = tp / len(pred), tp / len(true)
    return 2 * prec * rec / (prec + rec), prec, rec


# ---------------------------------------------------------------------------
# References by simulation (floor / realizable / omniscient). All model-free.
# ---------------------------------------------------------------------------
def _loud_order(n: int, reach: List[FrozenSet[int]]) -> List[int]:
    """Nodes by descending reachable-set size — the salience gradient (the false compass)."""
    return sorted(range(n), key=lambda v: (-len(reach[v]), v))


def naive_floor(spec: MechSpec) -> Tuple[float, float]:
    """The false-compass player: spend the budget poking the LOUDEST nodes and report every
    reachable pair as a direct edge (no reduction, no structure-reading). Returns (f1, prec).
    Its precision is exactly 'how wrong it is to treat what lights up as the wiring' — the
    deception magnitude, a genuine property of the graph (high for deep chains, ~1 for stars).
    """
    _, edges, reach, _ = expand(spec)
    order = _loud_order(spec.N, reach)[: spec.budget]
    pred = {(i, j) for i in order for j in reach[i]}
    score, prec, _ = f1(pred, edges)
    return score, prec


def realizable(spec: MechSpec) -> float:
    """The realizable ceiling (the normalizer): the best F1 a structure-reading player can
    reach under budget WITHOUT being handed the wiring. With the reachability observable the
    tasteful move is to poke widely and do transitive reduction -- recall is cheap (any poked
    parent captures its true edge), so the work is *precision*: stripping the transitive ghosts
    by poking the intermediates. We simulate it greedily -- add the poke that most improves the
    reduced-edge F1, up to budget. On a forest, poking is monotone (reduction never strips a
    true edge), so greedy poking the right parents approaches the achievable ceiling; floored at
    the no-inference floor since a realizable player can always fall back. Dumb, deterministic,
    agent-inaccessible f(spec, budget) -- the integrity floor is intact."""
    _, edges, reach, _ = expand(spec)
    n = spec.N
    poked: Set[int] = set()
    cur = 0.0
    for _ in range(min(spec.budget, n)):
        best_gain, best_v = 0.0, None
        for v in range(n):
            if v in poked:
                continue
            s, _, _ = f1(transitive_reduction(poked | {v}, reach), edges)
            if s - cur > best_gain:
                best_gain, best_v = s - cur, v
        if best_v is None:        # remaining unpoked nodes are leaves -> no more to learn
            break
        poked.add(best_v)
        cur, _, _ = f1(transitive_reduction(poked, reach), edges)
    return max(cur, naive_floor(spec)[0])


def references(spec: MechSpec) -> dict:
    """The bracket the student is measured against, all by simulation on the fixed graph:
    floor (false-compass naive reading), realizable (structure-reading ceiling), oracle
    (knows the wiring -> F1 1.0, kept for diagnostics), and the deception magnitude."""
    floor_score, floor_prec = naive_floor(spec)
    return {
        "floor_f1": round(floor_score, 4),
        "realizable_f1": round(realizable(spec), 4),
        "oracle_f1": 1.0,
        "naive_precision": round(floor_prec, 4),   # low => loud reading is very wrong
        "deception": round(1.0 - floor_prec, 4),   # fraction of loud-inferred edges that are false
    }


# ---------------------------------------------------------------------------
# Ramp (the learning gradient): coverage vs fraction of modules fully inferred. Structural,
# free. Modules are independent components, so this is linear by construction -- the property
# that lets a weak model climb (partial taste buys proportional coverage).
# ---------------------------------------------------------------------------
def ramp_curve(spec: MechSpec) -> List[float]:
    """curve[f] = mean fraction of EDGES recovered when you fully infer a random f-subset of
    the G modules (averaged over all f-subsets). Straight 0->1 line => a ramp, not a cliff."""
    edge_counts = [m.size - 1 for m in spec.modules]
    total = sum(edge_counts)
    G = len(spec.modules)
    curve = []
    for f in range(G + 1):
        subs = list(combinations(range(G), f))
        mean_edges = sum(sum(edge_counts[j] for j in sub) for sub in subs) / len(subs)
        curve.append(mean_edges / total if total else 0.0)
    return curve


def linearity_r2(curve: List[float]) -> float:
    """R^2 of `curve` against the straight line 0..1. ~1.0 => clean ramp."""
    G = len(curve) - 1
    line = [f / G for f in range(G + 1)]
    mean = sum(curve) / len(curve)
    ss_tot = sum((y - mean) ** 2 for y in curve)
    ss_res = sum((y - l) ** 2 for y, l in zip(curve, line))
    return 1.0 if ss_tot == 0 else 1.0 - ss_res / ss_tot
