"""The Chapter-2 world substrate: a segmented tape generated by a compact grammar,
plus everything the integrity floor needs to be a *dumb deterministic* judge — the
version-space determination, the DP oracle, the floor, and the smoothness curve.

The world is a hidden tape of M cells, each an integer color in 0..K-1. The tape is
partitioned into G contiguous **segments**; each segment is generated INDEPENDENTLY by
one member of a small known **family** of patterns:

    const(v)   : v, v, v, ...
    arith(v,s) : (v + s*i) mod K           (a "hidden step" the agent must read)
    alt(v,w)   : v, w, v, w, ...

The grammar STRUCTURE (segment boundaries + the family) is known to everyone; the SEED
(which pattern + which params per segment) is the genuinely hidden information that must
be probed. This is the Chapter-1 safe-eval invariant lifted from rule-lambdas to a
declarative spec: the smith would propose a validated spec, a deterministic expander
realizes it (here, `expand`), and model output never executes.

Why this shape (the design, in code):
- **Intrinsic-information weighting falls out of the structure, not a hand-picked list.**
  A probe is worth how many *other* cells it lets you determine. A long segment pinned by
  a couple of probes is worth many cells/probe; a short one, few. Maximizing plain
  per-cell coverage is therefore already value-of-information probing — no hand-assigned
  "interesting" weight that would smuggle our taste prior into the judge.
- **Ramp, not cliff (bet 2).** Segments are independent, so inferring one buys exactly its
  cells regardless of the others -> coverage is ~linear in the fraction inferred.
- **Determinism hands us the oracle (bet 1's ceiling).** On a fixed tape with a budget the
  optimal probe set is a small knapsack over per-segment value curves — computed exactly,
  model-free, by `oracle_determined`.
"""

from dataclasses import dataclass
from functools import lru_cache
from itertools import combinations
from typing import List, Tuple

KINDS = ("const", "arith", "alt")


@dataclass(frozen=True)
class Segment:
    kind: str              # one of KINDS
    params: Tuple[int, ...]  # const:(v,)  arith:(v,s)  alt:(v,w)
    length: int


@dataclass(frozen=True)
class TapeSpec:
    """A hand-built (Chapter-2: smith-proposed) world. Compact by construction: a handful
    of segments, each a family member + params + length. `budget` is the scarce probe
    allowance the judge normalizes against."""
    name: str
    K: int
    segments: Tuple[Segment, ...]
    budget: int

    @property
    def M(self) -> int:
        return sum(s.length for s in self.segments)

    def bounds(self) -> List[Tuple[int, int]]:
        """Global [start, end) index range of each segment (the structure both agents see;
        the agent infers only the pattern WITHIN each range)."""
        out, off = [], 0
        for s in self.segments:
            out.append((off, off + s.length))
            off += s.length
        return out


# ---------------------------------------------------------------------------
# Deterministic expander: spec -> the hidden tape. Bounded by construction (a flat
# tape of sum(lengths)); no recursion, so no fuel needed at this size.
# ---------------------------------------------------------------------------
def realize_segment(seg: Segment, K: int) -> Tuple[int, ...]:
    n = seg.length
    if seg.kind == "const":
        (v,) = seg.params
        return tuple(v % K for _ in range(n))
    if seg.kind == "arith":
        v, s = seg.params
        return tuple((v + s * i) % K for i in range(n))
    if seg.kind == "alt":
        v, w = seg.params
        return tuple((v if i % 2 == 0 else w) % K for i in range(n))
    raise ValueError(f"unknown segment kind {seg.kind!r}")


def expand(spec: TapeSpec) -> Tuple[int, ...]:
    """Realize the full hidden tape (the answer key — lives in the world plane only)."""
    out: List[int] = []
    for seg in spec.segments:
        out.extend(realize_segment(seg, spec.K))
    return tuple(out)


# ---------------------------------------------------------------------------
# The family version space + determination (the dumb deterministic core the judge and
# the oracle both run on). Everything here is pure f(structure, observations).
# ---------------------------------------------------------------------------
@lru_cache(maxsize=None)
def seg_candidates(n: int, K: int) -> Tuple[Tuple[int, ...], ...]:
    """Every value-sequence the family can produce for a length-n segment over K colors.
    The true segment is always one of these; probing collapses this set."""
    seqs = set()
    for v in range(K):
        seqs.add(tuple(v for _ in range(n)))                       # const
        for s in range(K):
            seqs.add(tuple((v + s * i) % K for i in range(n)))     # arith
        for w in range(K):
            seqs.add(tuple((v if i % 2 == 0 else w) for i in range(n)))  # alt
    return tuple(sorted(seqs))


def determined_count(n: int, K: int, idxs: Tuple[int, ...], vals: Tuple[int, ...]) -> int:
    """How many of the n cells are LOGICALLY pinned once you've observed `vals` at local
    `idxs` — i.e. all family members still consistent agree on them. This is the
    information a probe set yields: 'how much knowing it collapses the rest.'"""
    cands = seg_candidates(n, K)
    consistent = [s for s in cands if all(s[i] == v for i, v in zip(idxs, vals))]
    if not consistent:
        return 0  # unreachable for true observations; guards against bad input
    return sum(1 for j in range(n) if len({s[j] for s in consistent}) == 1)


# ---------------------------------------------------------------------------
# The DP oracle and the no-inference floor (the model-free references that bracket the
# student). Both are computed on the fixed tape; neither uses an LLM.
# ---------------------------------------------------------------------------
def seg_value_curve(true_seq: Tuple[int, ...], K: int) -> List[int]:
    """value[k] = max cells the oracle can determine in THIS segment with k well-placed
    probes (it knows the true values, so it never wastes a probe). Saturates at the
    segment length. The shape of this curve is the segment's intrinsic VoI."""
    n = len(true_seq)
    curve = [0]
    for k in range(1, n + 1):
        best = curve[-1]
        for idxs in combinations(range(n), k):
            vals = tuple(true_seq[i] for i in idxs)
            best = max(best, determined_count(n, K, idxs, vals))
            if best == n:
                break
        curve.append(best)
        if best == n:
            curve.extend([n] * (n - k))  # already fully pinned; stays saturated
            break
    return curve


def oracle_determined(spec: TapeSpec, budget: int = None) -> int:
    """Max cells determinable across the whole tape under the probe budget — a knapsack
    over independent per-segment value curves. The omniscient-grammar ceiling: it knows
    where the information is, so it never wastes a probe and infers everything a probe set
    permits. (See WORLD_DESIGN -> 'omniscient oracle may be too strong a denominator'.)"""
    B = spec.budget if budget is None else budget
    curves = [seg_value_curve(realize_segment(s, spec.K), spec.K) for s in spec.segments]
    dp = [0] * (B + 1)  # dp[b] = best cells determined using b probes over processed segs
    for curve in curves:
        nxt = [0] * (B + 1)
        for b in range(B + 1):
            best = 0
            for k in range(min(b, len(curve) - 1) + 1):
                best = max(best, dp[b - k] + curve[k])
            nxt[b] = best
        dp = nxt
    return dp[B]


def floor_determined(spec: TapeSpec, budget: int = None) -> int:
    """A no-inference prober determines only the cells it directly probed (it never reads
    the grammar to predict the unseen). The dumb baseline the student must beat to show
    that *inference*, not just probing, is doing the work."""
    B = spec.budget if budget is None else budget
    return min(B, spec.M)


# ---------------------------------------------------------------------------
# Smoothness (bet 2): coverage as a function of how much of the grammar you inferred.
# Computed structurally on the fixed tape — no LLM, free.
# ---------------------------------------------------------------------------
def smoothness_curve(spec: TapeSpec) -> List[float]:
    """curve[f] = mean fraction of cells *determined* when you fully infer a random
    f-subset of the G segments (averaged over all subsets of that size). A straight line
    from 0 -> 1 means partial grammar buys proportional coverage (a ramp); a hockey-stick
    means a cliff."""
    sizes = [s.length for s in spec.segments]
    G, M = len(sizes), spec.M
    curve = []
    for f in range(G + 1):
        subsets = list(combinations(range(G), f))
        mean_cells = sum(sum(sizes[j] for j in sub) for sub in subsets) / len(subsets)
        curve.append(mean_cells / M)
    return curve


def linearity_r2(curve: List[float]) -> float:
    """R^2 of `curve` against the straight line 0..1 over f=0..G. ~1.0 => clean ramp."""
    G = len(curve) - 1
    line = [f / G for f in range(G + 1)]
    mean = sum(curve) / len(curve)
    ss_tot = sum((y - mean) ** 2 for y in curve)
    ss_res = sum((y - l) ** 2 for y, l in zip(curve, line))
    return 1.0 if ss_tot == 0 else 1.0 - ss_res / ss_tot
